/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Mistong.Services.OrderService
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class OrderInfo : TBase
  {

    public int? OrderID { get; set; }

    public string OrderNo { get; set; }

    public double? OrderAmount { get; set; }

    public OrderInfo() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                OrderID = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                OrderNo = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Double) {
                OrderAmount = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("OrderInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (OrderID != null) {
          field.Name = "OrderID";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(OrderID.Value);
          oprot.WriteFieldEnd();
        }
        if (OrderNo != null) {
          field.Name = "OrderNo";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(OrderNo);
          oprot.WriteFieldEnd();
        }
        if (OrderAmount != null) {
          field.Name = "OrderAmount";
          field.Type = TType.Double;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(OrderAmount.Value);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("OrderInfo(");
      bool __first = true;
      if (OrderID != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OrderID: ");
        __sb.Append(OrderID);
      }
      if (OrderNo != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OrderNo: ");
        __sb.Append(OrderNo);
      }
      if (OrderAmount != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OrderAmount: ");
        __sb.Append(OrderAmount);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
